language: python
python:
  - "3.3"
virtualenv:
      system_site_packages: true
before_install: ./ci/before_install.sh
install:
  - "pip install markdown whoosh"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: python test.py
