language: python

python:
  - "3.3"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3-pyqt5

install:
  - "pip install markdown whoosh"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: python test.py
