language: python
python:
  - "3.3"
virtualenv:
      system_site_packages: true
before_install:
     - sudo apt-get update -qq
     - sudo apt-get install -qq python3-pyqt4
install:
  - "pip install markdown whoosh"
script: python3 test.py
