language: python
sudo: required
dist: trusty

python:
  - "3.3"

virtualenv:
  system_site_packages: true

install:
  - sudo apt-get update -q
  - sudo apt-get install python3-pyqt5 -y
  - "pip install markdown whoosh"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: python test.py
